export const subscription = {
  active: true,
  dirty: true,
  dirtyFields: true,
  dirtyFieldsSinceLastSubmit: true,
  dirtySinceLastSubmit: true,
  modifiedSinceLastSubmit: true,
  error: true,
  errors: true,
  hasSubmitErrors: true,
  hasValidationErrors: true,
  initialValues: true,
  invalid: true,
  modified: true,
  pristine: true,
  submitError: true,
  submitErrors: true,
  submitFailed: true,
  submitting: true,
  submitSucceeded: true,
  touched: true,
  valid: true,
  validating: true,
  values: true,
  visited: true,
};
